### ISSUE TITLE
Does not build with nodejs 11

### ISSUE THREAD

**Issue by zeule** [ChapelR/tweego-setup#2]
```
> tweego-setup@1.0.0 build /home/xxx/games/who-am-i
> gulp build && tweego -f $npm_package_config_format --head=src/HEAD.html -o dist/index.html project && opn dist/index.html

fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/home/eugene/games/who-am-i/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/eugene/games/who-am-i/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/eugene/games/who-am-i/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
```

Suggestion from [gulp issue](https://github.com/gulpjs/gulp/issues/2246) helps

**Comment by ChapelR** [comment]
Thanks. That link is super helpful. I'll look into this as soon as I can.

**Comment by ChapelR** [comment]
Forgot to close this. Works with Node 11 and 12 since v1.1.0.
